//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PACEBuzz.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public string resetShortcutKey {
            get {
                return ((string)(this["resetShortcutKey"]));
            }
            set {
                this["resetShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool resetShortcutShift {
            get {
                return ((bool)(this["resetShortcutShift"]));
            }
            set {
                this["resetShortcutShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool resetShortcutControl {
            get {
                return ((bool)(this["resetShortcutControl"]));
            }
            set {
                this["resetShortcutControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F11")]
        public string nextBuzzShortcutKey {
            get {
                return ((string)(this["nextBuzzShortcutKey"]));
            }
            set {
                this["nextBuzzShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nextBuzzShortcutShift {
            get {
                return ((bool)(this["nextBuzzShortcutShift"]));
            }
            set {
                this["nextBuzzShortcutShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nextBuzzShortcutControl {
            get {
                return ((bool)(this["nextBuzzShortcutControl"]));
            }
            set {
                this["nextBuzzShortcutControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F12")]
        public string countdownShortcutKey {
            get {
                return ((string)(this["countdownShortcutKey"]));
            }
            set {
                this["countdownShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool countdownShortcutShift {
            get {
                return ((bool)(this["countdownShortcutShift"]));
            }
            set {
                this["countdownShortcutShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool countdownShortcutControl {
            get {
                return ((bool)(this["countdownShortcutControl"]));
            }
            set {
                this["countdownShortcutControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool lightCheckShortcutShift {
            get {
                return ((bool)(this["lightCheckShortcutShift"]));
            }
            set {
                this["lightCheckShortcutShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool lightCheckShortcutControl {
            get {
                return ((bool)(this["lightCheckShortcutControl"]));
            }
            set {
                this["lightCheckShortcutControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>beep1.wav</string>
  <string>beep2.wav</string>
  <string>beep3.wav</string>
  <string>beep4.wav</string>
  <string>beep5.wav</string>
  <string>beep6.wav</string>
  <string>beep7.wav</string>
  <string>beep8.wav</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection buzzSounds {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["buzzSounds"]));
            }
            set {
                this["buzzSounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool alwaysOnTop {
            get {
                return ((bool)(this["alwaysOnTop"]));
            }
            set {
                this["alwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool blink {
            get {
                return ((bool)(this["blink"]));
            }
            set {
                this["blink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool allowBuzzerCancels {
            get {
                return ((bool)(this["allowBuzzerCancels"]));
            }
            set {
                this["allowBuzzerCancels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showInTaskBar {
            get {
                return ((bool)(this["showInTaskBar"]));
            }
            set {
                this["showInTaskBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int countdownLengthInSeconds {
            get {
                return ((int)(this["countdownLengthInSeconds"]));
            }
            set {
                this["countdownLengthInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool firstPlayerCanCancel {
            get {
                return ((bool)(this["firstPlayerCanCancel"]));
            }
            set {
                this["firstPlayerCanCancel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool quitPrompt {
            get {
                return ((bool)(this["quitPrompt"]));
            }
            set {
                this["quitPrompt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F8")]
        public string previousBuzzShortcutKey {
            get {
                return ((string)(this["previousBuzzShortcutKey"]));
            }
            set {
                this["previousBuzzShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool previousBuzzShortcutShift {
            get {
                return ((bool)(this["previousBuzzShortcutShift"]));
            }
            set {
                this["previousBuzzShortcutShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool previousBuzzShortcutControl {
            get {
                return ((bool)(this["previousBuzzShortcutControl"]));
            }
            set {
                this["previousBuzzShortcutControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lightCheckShortcutKey {
            get {
                return ((string)(this["lightCheckShortcutKey"]));
            }
            set {
                this["lightCheckShortcutKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arcade")]
        public string buzzerType {
            get {
                return ((string)(this["buzzerType"]));
            }
            set {
                this["buzzerType"] = value;
            }
        }
    }
}
